### PR TITLE
build: use forked icons generator

### PR DESCRIPTION
**Pull request by AxelPeter**
There is currently a problem with the Icons generator that we use (see https://github.com/Workshape/icon-font-generator/issues/34 and https://github.com/fontello/svg2ttf/issues/48).

The vertical metrics are badly set and result in wrong vertical alignment for icons on Windows.
There is a fix that waits to be merge here, but the repository seems to be inactive: https://github.com/fontello/svg2ttf/pull/82.

I've created a fork of `icon-font-generator`, `webfonts-generator` and `svg2ttf` to apply the fix.
Even if the icons have been fixed with a previous commit, I regenerate them with the forked package.

ref: UK-156

### CODE REVIEW

**Comment by antleblanc** [comment]
Sorry to come late regarding these changes but I'm having trouble to understand the main issue.

You mentioning and issue with the package called `svg2ttf` but correct me if I'm wrong,
we only support `woff2` and `woff` format (see: https://github.com/ovh/ovh-ui-kit/pull/263).

We can also preview it here: https://unpkg.com/browse/@ovh-ux/ui-kit@4.0.9/dist/fonts/oui-icons/ (no `ttf` font generated are published).

After digging a bit it seems that we never rely on `svg2ttf` for the generated fonts.
Here is how font are generated: https://github.com/sunflowerdeath/webfonts-generator/blob/master/src/generateFonts.js#L72-L88

In addition to that we are stick with extra forks directly into your userland which is never
a good mid-long term solution.

And I've also noticed that [webfonts-generator](https://github.com/sunflowerdeath/webfonts-generator) is archived since a long time ago so maybe we can think about an alternative in the way that we are managing Icon Fonts.

**Comment by AxelPeter** [comment]
Your example shows clearly that we use `ttf2woff` and `ttf2woff2`. I think that the name is self-explaining :)

`svg2ttf` is used to created a TTF file based on SVG files.
`webfont-generator` serves now to create all the other webfonts, with the TTF file as a base.
`icon-font-generator` works more like a CLI to scaffold all of this.

I never said that this solution will stay in the long term. But finding a new commandline webfont icon generator is not easy. One that create the files on demand, and create a LESS file with the Icons content value. So in the case of generating the fonts in the future, I don't have to think of this issue again.

I've already searched after a new one to change this one before this issue. And none cover all of this, without having to create a new one.

**Comment by puzrin** [comment]
@AxelPeter FYI:

1. I've updated `svg2ttf` with fix of Windows line height. You probably don't need fork anymore.
2. I'd suggest to replace very old `ttf2woff2` with `wawoff2` https://github.com/fontello/wawoff2

**Comment by AxelPeter** [comment]
@puzrin Thank you ! I'll take a look at this :)

**Pull request merged**
