### PR TITLE
fix(select): reset cursor on change

### PR DESCRIPTION
**Pull request by y4nnL**
## oui-select
- [X] Reset the cursor id when the load property has changed

### CODE REVIEW

**Review by anooparveti — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report yarn-build#2758.0 ✘  
* build & test
  * build ✔ 
  * test ✘

**Comment by ovh-cds** [comment]
CDS Report yarn-build#2758.1 ✘  
* build & test
  * build ✔ 
  * test ✘

**Comment by ovh-cds** [comment]
CDS Report yarn-build#2758.1 ✘  
* build & test
  * build ✔ 
  * test ✘

**Review by ghyenne — APPROVED** [review]

**Review by ghyenne — CHANGES_REQUESTED** [review]
The tests aren't good.

**Review by ghyenne — APPROVED** [review]

**Pull request merged**
