### PR TITLE
feat(icons): add PlatformSh and cloud essential icons

### PR DESCRIPTION
**Pull request by radireddy**
add new PlatformSh icon

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

## Title of the Pull Requests 

add new PlatformSh and cloud essential icons

### Description of the Change

Added PlatformSh icon

### CODE REVIEW

**Review by antleblanc — CHANGES_REQUESTED** [review]
Both `*.svg` files has the same ID `Calque_1` and it uses also strange `ID`
attributes on some `<path>` elements.
They also have strange `data-name` attributes values.

Could you please make sure to bring here only optimized SVG?

Thank you!

**Comment by radireddy** [comment]
> Both `*.svg` files has the same ID `Calque_1` and it uses also strange `ID`
> attributes on some `<path>` elements.
> They also have strange `data-name` attributes values.
> 
> Could you please make sure to bring here only optimized SVG?
> 
> Thank you!

@antleblanc I checked on this and got a confirmation that these are the final icons. I have removed the name and id attribute from SVG. I did not find a name and ID on any of the SVG icons we are using. This will be consistent.

**Review by antleblanc — CHANGES_REQUESTED** [review]
Could you please make sure that both SVG are well sorted into the following story:
- packages/apps/workshop/stories/design-system/content/icons.stories.js

Thank you!

**Comment by ganeshkumar1989** [comment]
> Could you please make sure that both SVG are well sorted into the following story:
> 
> * packages/apps/workshop/stories/design-system/content/icons.stories.js
> 
> Thank you!

This is done. Thanks!

**Review by antleblanc — APPROVED** [review]

**Pull request merged**
