### PR TITLE
Release v5.0.0

### PR DESCRIPTION
**Pull request by JeremyDec**
### Description of the Change

:warning: New major version as the following breaking change is embedded 4ea7186

7aa3efe - feat: add trusted icon #712

### CODE REVIEW

**Review by marie-j — DISMISSED** [review]

**Review by ganeshkumar1989 — DISMISSED** [review]

**Comment by antleblanc** [comment]
**thought:** As a new Major version is targeted here, maybe we can take the opportunity to get rid of some old/deprecated classes in order to be able to reduce the amount of css rules.

See following existing comment `/* Deprecated: Support for old classname */` across the codebase.

**Comment by JeremyDec** [comment]
@antleblanc here is the PR to remove these deprecated less class > https://github.com/ovh/ovh-ui-kit/pull/729.

It will requires some adaptation of manager applications using this new major version, I'll check the places to adapt the code regarding those (some of them are still used).

**Comment by ganeshkumar1989** [comment]
@JeremyDec , if that is going to take time, can we have a minor release for 7aa3efe - feat: add trusted icon #712 ? We are waiting for the icon to be used in the Manager and it would be great if the release can happen soon.

**Comment by JeremyDec** [comment]
@ganeshkumar1989 the work to adapt the manager is already done (currently in draft PR), so it won't take time to adapt, see: https://github.com/ovh/manager/pull/5350

**Review by antleblanc — APPROVED** [review]

**Review by ganeshkumar1989 — APPROVED** [review]

**Pull request merged**
